######################################################################
# Automatically generated by qmake (3.0) Mon Feb 29 17:12:48 2016
######################################################################

HEADERS += qceckeyboardmanager.h
SOURCES += main.cpp \
    qceckeyboardmanager.cpp

LOCALDIR = $${TOPLEVEL}/local
INCLUDEPATH += .
INCLUDEPATH += $${LOCALDIR}/include

# Our plugin assumes it is shipped with libcec in the same path
LIBS += -L$${LOCALDIR}/lib -lcec -lbcm_host -ldl

TARGET = qceckeyboardplugin

PLUGIN_TYPE = generic
PLUGIN_EXTENDS = -
PLUGIN_CLASS_NAME = QCECKeyboardPlugin
load(qt_plugin)

DESTDIR=$${TOPLEVEL}/out

QT += platformsupport-private

OTHER_FILES += \
    ceckeyboard.json

